_target_: src.networks.mlp.Fully_connected
res: 1
hidden_dim: 64
input_dim: ${datamodule.input_dim}
output_dim: ${datamodule.input_dim}    
num_layer: 2
activation: 'Prelu'
full_activ: 0
batch_nml: 0
dropout: 0.02