_target_: pytorch_lightning.Trainer

gpus: [7]

# min_epochs: 1
max_epochs: 20

progress_bar_refresh_rate: 5
resume_from_checkpoint: null
weights_summary: null
reload_dataloaders_every_n_epochs: ${epochs_per_Pk}
# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
log_every_n_steps: 50
