module:
  _target_: src.models.bayesian_model.BayesianModule

lr_g: 1.0e-3 #tune
lr_h: 1.0e-3
schedule_learning_rate: 0
lr_schedule_scale_t: 0.4 #tune
lr_schedule_scale_h: 0.4 #tune  
lr_schedule_epoch: 20 #tune  
weight_decay: 1.0e-7

T_net:
  _target_: src.networks.mlp.Fully_connected
  res: 1
  hidden_dim: 64
  input_dim: ${datamodule.input_dim}
  output_dim: ${datamodule.input_dim}    
  num_layer: 2
  activation: 'Prelu'
  full_activ: 1
  batch_nml: 0
  dropout: 0.02
  quadr: 0
  sigmoid: 0
  
h_net:
  _target_: src.networks.mlp.Fully_connected  
  hidden_dim: 64 
  input_dim: ${datamodule.input_dim}
  output_dim: 1
  num_layer: 2 
  activation: 'Prelu'
  final_actv: 'Prelu'  
  quadr: 1
  sigmoid: 0

non_log_ratio: ${model.h_net.quadr}
smooth_h: 0
crank_nicolson: 0

N_outer_ITERS: 1
N_inner_ITERS: 3
energy_type: "kl_density"
dk_formula: 0
step_a: 0.1

epochs_per_Pk: ${epochs_per_Pk}
epochs_per_val: 1